typography_spectrum: 0.40454643990447986
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.1442095575251128
  lightness: 0.6171906251763685
  saturation: 0.30330376346125315
  rhythmicContrast: 0.3103373409128093
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.1227991660783012
author:
  name: Allyn Reid
  url: www.heavenonearthtv.com
  email: allyntoday@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/81e09d9e-3190-4384-9863-df226fdd4abb.png
name: heaven on earth
url: 'http://www.heavenonearthtv.com'
navigation:
  - name: prima portfolio
    id: 9f1330c1-3344-4b4a-85c5-379a610d887e
    type: content
  - name: artist statement
    id: 6f17845e-f073-46b2-b4bc-6641db1877c5
    type: content
  - name: about
    id: 75a7fb72-6603-428a-a15d-cb79e666f63e
    type: content
  - name: stay in touch
    id: 38a2978c-eb08-4ab7-aefc-e3e380b4339b
    type: content
  - name: teacher training program
    id: da56ecc5-8852-4907-9416-ad88c70a32e4
    type: content
title: a collection of possibilities
content: []
description: by allyn reid
